#!/usr/bin/env -S pkgx +llama.cpp +huggingface-cli=0.19.4 +gum bash

# https://twitter.com/EMostaque/status/1732912442282312099 ?

set -eo pipefail

model="$(huggingface-cli download TheBloke/dolphin-2.1-mistral-7B-GGUF dolphin-2.1-mistral-7b.Q4_K_M.gguf)"

D="$(which llama.cpp)"
D="$(dirname $D)"
D="$(cd "$D/.." && pwd)"

prompt="$(cat)"

exec "$D/bin/llama.cpp" \
	--model "$model" \
	--prompt "summarize this: $prompt"
