#!/usr/bin/env -S pkgx +git +python~3.10 +wget +gum +huggingface-cli=0.19.4 bash -eo pipefail

PREFIX="${XDG_DATA_HOME:-$HOME/.local}"
SRCDIR="${PREFIX}/ComfyUI"

if [ $(uname) != Darwin ]; then
  gum format \
    '# untested on linux' \
    'please open a ticket at https://github.com/mxcl/mash if it doesn’t work.'
fi

gum format <<EoMD
# Comfy UI

* generated images are saved to \`$SRCDIR/output\`
* download additional models to \`$PREFIX/share/models\`

> NOTE! You will need to download models yourself.
> If you prefer run \`mash ai ui-sd\` once to have it download a default model.
EoMD

echo  #spacer

if [ ! -f "$SRCDIR"/main.py ]; then
	gum confirm "clone to $SRCDIR?"
	mkdir -p "$SRCDIR"
	git -C "$SRCDIR"/.. clone https://github.com/comfyanonymous/ComfyUI $(basename "$SRCDIR")
	cd "$SRCDIR"
else
	cd "$SRCDIR"
	git fetch -pft
	git reset --hard origin/master
fi

echo  #spacer

### setup reusable model paths
mkdir -p "$PREFIX/share/models/checkpoints"
mkdir -p "$PREFIX/share/models/vae"
mkdir -p "$PREFIX/share/models/embeddings"
mkdir -p "$PREFIX/share/models/loras"

cd models
rm -rf checkpoints
ln -s ../../share/models/checkpoints
rm -rf VAE
ln -s ../../share/models/vae
rm -rf loras
ln -s ../../share/models/loras
rm -rf embeddings
ln -s ../../share/models/embeddings
cd ..

### venv
if [ ! -d venv ]; then
  python -m venv venv
  source venv/bin/activate
  if [ $(uname) = Darwin ]; then
    pip install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu
  else
    # nvidia only
    # see https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#amd-gpus-linux-only
    pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121
  fi
  pip install -r requirements.txt
else
  source venv/bin/activate
fi

### run
if [ $(uname) = Darwin ]; then
  exec python main.py --force-fp16
else
  exec python main.py
fi
