#!/usr/bin/env -S pkgx +git +gum +python~3.10 +ffmpeg.org bash -eo pipefail

PREFIX="${XDG_DATA_HOME:-$HOME/.local}"
SRCDIR="${PREFIX}/FaceFusion"
XDG_DOCUMENTS_DIR="${XDG_DOCUMENTS_DIR:-$HOME/Documents}"
OUTDIR="$XDG_DOCUMENTS_DIR/FaceFusion"

gum format \
	'# FaceFusion' \
	"* generated images are saved to \`$OUTDIR\`"

echo  # spacer

if [ ! -f "$SRCDIR"/run.py ]; then
	gum confirm "clone to $SRCDIR?"
	mkdir -p "$SRCDIR"
	git -C "$SRCDIR"/.. clone https://github.com/facefusion/facefusion $(basename "$SRCDIR")

	cd "$SRCDIR"

	python3.10 -m venv venv
	source venv/bin/activate
	python install.py
else
	cd "$SRCDIR"
	git pull origin master --no-rebase
	source venv/bin/activate
fi

# or it fails lol
mkdir -p "$OUTDIR"

exec python run.py --output "$OUTDIR" "$@"
