#!/usr/bin/env -S pkgx +git +python~3.10 +wget +gum +huggingface-cli=0.19.4 bash -eo pipefail

PREFIX="${XDG_DATA_HOME:-$HOME/.local}"
SRCDIR="${PREFIX}/sd-webui"

gum format <<EoMD
# Stable Diffusion web UI

* generated images are saved to \`$SRCDIR/outputs\`
* download additional Stable Diffusion models to \`$PREFIX/share/models\`

EoMD

echo  #spacer

if [ ! -f "$SRCDIR"/webui.sh ]; then
	gum confirm "clone to $SRCDIR?"
	mkdir -p "$SRCDIR"
	git -C "$SRCDIR"/.. clone https://github.com/AUTOMATIC1111/stable-diffusion-webui $(basename "$SRCDIR")

	cd "$SRCDIR"

	# needed in order to fix the `gradio` bug below
	./webui.sh --no-download-sd-model --exit

	# gradio 3.41.2 fails to load anything if any part in the install path has a `.` prefix 🤦‍♂️
    # https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13292
    # FIXME should stop doing this when fixed
    # https://github.com/gradio-app/gradio/pull/4303
    sed -i.bak '/is_dotfile =/s/= .*/= False/' "$SRCDIR/venv/lib/python3.10/site-packages/gradio/routes.py"
else
	cd "$SRCDIR"
	git fetch -pft
	git reset --hard origin/master
fi

echo  #spacer

# setup reusable model paths
mkdir -p "$PREFIX/share/models/checkpoints"
mkdir -p "$PREFIX/share/models/embeddings"
mkdir -p "$PREFIX/share/models/loras"
mkdir -p "$PREFIX/share/models/vae"

cd models
rm -rf Stable-diffusion
ln -s ../../share/models/checkpoints Stable-diffusion
rm -rf VAE
ln -s ../../share/models/vae VAE
rm -rf Lora
ln -s ../../share/models/loras Lora
cd ..
rm -rf embeddings
ln -s ../share/models/embeddings

dl_model() {
	final="$SRCDIR/models/Stable-diffusion/$3.safetensors"
	if [ ! -f "$final" ]; then
		model="$(huggingface-cli download $1 $2.safetensors)"
		ln -sf "$model" "$final"
	fi
	ARGS=($4 --ckpt="$final")
}

case $(gum choose --header='model?' SD1.5 SD2.0 SD2.1 SDXL-1.0) in
SD1.5)
	# sd-webui usually downloads this automatically itself, but let’s be consistent
	# in using huggingface-cli
	dl_model runwayml/stable-diffusion-v1-5 v1-5-pruned-emaonly SD1.5
	gum format "# IMPORTANT!" "ensure image width and height are set to 512"
	;;
SD2.0)
	dl_model stabilityai/stable-diffusion-2 768-v-ema SD2.0
	gum format "# IMPORTANT!" "set image width and height to 768"
	;;
SD2.1)
	dl_model webui/stable-diffusion-2-1 v2-1_768-ema-pruned SD2.1 --no-half
	gum format "# IMPORTANT!" "set image width and height to 768"
	;;
SDXL-1.0)
	dl_model stabilityai/stable-diffusion-xl-base-1.0 sd_xl_base_1.0_0.9vae SDXL1.0
	gum format "# IMPORTANT!" "set image width and height to 1024"
	;;
esac

echo  #spacer

exec ./webui.sh "${ARGS[@]}" "$@"
