#!/usr/bin/env -S pkgx +git +gum +python~3.10 +ffmpeg.org bash -eo pipefail

PREFIX="${XDG_DATA_HOME:-$HOME/.local}"
SRCDIR="${PREFIX}/sherlock"
XDG_DOCUMENTS_DIR="${XDG_DOCUMENTS_DIR:-$HOME/Documents}"
OUTDIR="$XDG_DOCUMENTS_DIR/Sherlock"

gum format \
	'# Sherlock' \
	"* outputs to \`$OUTDIR\`"

echo  # spacer

if [ ! -d "$SRCDIR"/sherlock ]; then
	gum confirm "clone to $SRCDIR?"
	mkdir -p "$SRCDIR"
  git -C "$SRCDIR"/.. clone https://github.com/sherlock-project/sherlock $(basename "$SRCDIR")

	cd "$SRCDIR"

	python3.10 -m venv venv
	source venv/bin/activate
	pip install -r requirements.txt
else
	cd "$SRCDIR"
	git pull origin master --no-rebase
	source venv/bin/activate
fi

exec python sherlock --folderoutput "$OUTDIR" "$@"
