#!/usr/bin/env -S pkgx +gh +git +gum +bpb bash

set -eo pipefail

gum format --<<EOMD
# simple setup for git GPG

*signing your commits is important for the security of the entire software industry, both open and closed*

## what to expect from this script

* installs \`/usr/local/bin/bpb\`†
* configures \`git\` to use it
* optionally, adds your GPG key to GitHub

> † \`bpb\` is a much simpler way to sign your commits than using GnuGPG
> https://github.com/withoutboats/bpb
EOMD

gum confirm "shall we continue?"

if [ ! -f /usr/local/bin/bpb ]; then
  gum format -- 'installing \`bpb\`, this requires sudo'

  sudo pkgx install bpb
fi

if ! test -f ~/.bpb_keys.toml; then
	gum format "k next up let’s configure your GPG key"

	user="$(gum input --prompt 'what’s your name? ')"
	email="$(gum input --prompt 'what’s your email? ')"
	bpb init "$user <$email>"

	GENERATED_KEY=1
else
	GENERATED_KEY=0
fi

gum format "configuring git to use \`bpb\`…"

git config --global gpg.program bpb
git config --global commit.gpgsign true

if (($GENERATED_KEY)); then
	middle=<<-EOMD
		your GPG key was generated into ~/.bpb_keys.toml
		now add your gpg key to your account:
		> https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account
		EOMD
else
	middle="\`bpb\` was already configured with a GPG key before we were invoked"
fi

if gum confirm "shall we add \`bpb\` to your GitHub account?"; then
	gum format "first, we need to add the \`write:gpg_key\` scope to your \`gh\` authentication"

	# authenticate with gh on web with https and extra permission to write gpg_key
	gh auth login -h github.com -p https -s write:gpg_key -w

	# pipe bpb public key to gh
	bpb print | gh gpg-key add -
else
	gum format --<<-EOMD
		k, just add your gpg key to your github account by yourself:

		> https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account

		You can get your gpg key with \`bpb print\`
		EOMD
fi

gum format <<EOMD
# done!

$middle

check out the \`bpb\` README for my information about \`bpb\`

> https://github.com/withoutboats/bpb

# help improve this script!
* allow it to port an existing GnuGPG key over
* support for other coding hubs
EOMD

echo  # spacer
